# Generated by Django 3.1.3 on 2020-11-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topmovie',
            name='rating',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
