# Generated by Django 3.1.3 on 2020-11-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_topmovie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='topmovie',
            name='director',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
