# Generated by Django 3.1.3 on 2020-11-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_topmovie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='topmovie',
            name='cast',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
